import spacy
from sentence_transformers import SentenceTransformer, util
input_sentence = "Am o obsesie cu mâncatul"


psychiatric_templates = {
    "Tulburarea depresivă majoră": [
        "Nu mai găsesc plăcere în nimic",
        "Sunt trist tot timpul",
        "Nu mai am energie să fac nimic",
        "Mă simt inutil și lipsit de speranță",
        "Nu dorm bine noaptea",
        "Plâng fără motiv",
        "Mă simt vinovat mereu",
        "Viața nu mai are rost",
        
        "M-am izolat de prieteni și familie",
        "Nu mai pot să mă concentrez pe nimic",
        "Am pierdut sau câștigat mult în greutate fără să vreau",
        "Nu mă mai interesează ce se întâmplă în jurul meu",
        "Mă simt lent, ca și cum aș merge prin apă",
        "Sunt iritabil și mă enervez ușor",
        "Mă trezesc dimineața foarte devreme și nu mai pot adormi",
        "Mă simt epuizat tot timpul, indiferent cât dorm",
        "Mă gândesc adesea la moarte sau sinucidere",
        "Totul mi se pare un efort imens",
        "Nu mă mai îngrijesc de aspectul meu",
        "Am sentimentul că nimănui nu-i pasă de mine",
        "Simt un gol în interior care nu poate fi umplut",
        "Nimic nu mă mai bucură",
        "Simt că sunt o povară pentru ceilalți",
        "Îmi este greu să iau decizii simple",
        "Am probleme de memorie și concentrare",
        "Nu am chef să mă dau jos din pat dimineața",
        "Am gânduri negative în permanență",
        "Nu mai visez la viitor"
    ],
    
    "Tulburare de stres posttraumatic": [
        "Retrăiesc mereu ce s-a întâmplat",
        "Am coșmaruri în fiecare noapte",
        "Sunetele puternice mă sperie",
        "Evit orice îmi amintește de traumă",
        "Mă simt în pericol tot timpul",
        "Am coșmaruri despre ce s-a întâmplat",
        "Retrăiesc momentul",
        "Simt că se întâmplă din nou",
        "Evit locurile care îmi amintesc de asta",
        "Evit persoanele care îmi amintesc de ce s-a întâmplat",
        "Sunt mereu în alertă",
        "Nu pot să mă relaxez niciodată",
        "Mă sperii ușor",
        "Tresar la orice zgomot",
        "Mă simt detașat de ceilalți",
        "Mă simt înstrăinat de ceilalți",
        "Nu-mi amintesc părți importante din ce s-a întâmplat",
        
        "Am flashback-uri în timpul zilei",
        "Când mă gândesc la ce s-a întâmplat, încep să tremur și să transpir",
        "Nu pot să dorm fără lumină aprinsă",
        "Am devenit foarte vigilent, mereu în gardă",
        "Mă trezesc țipând noaptea",
        "Evit să vorbesc despre ce s-a întâmplat",
        "Mă simt ca și cum nu aș mai fi eu însumi după ce s-a întâmplat",
        "Am sentimentul că viața mea s-a oprit în momentul traumei",
        "Nu mai simt emoții la fel ca înainte",
        "Mă enervez foarte repede și explodez fără motiv",
        "Am dificultăți în a-mi aminti lucruri din viața de zi cu zi",
        "Nu mai pot să simt bucurie sau iubire",
        "Viitorul mi se pare scurt și întunecat",
        "Mă simt rușinat pentru ce s-a întâmplat",
        "Mă învinovățesc pentru ce s-a întâmplat",
        "Reacționez exagerat la situații obișnuite",
        "Simt că nimeni nu poate înțelege prin ce am trecut",
        "Nu îmi mai pot face planuri de viitor",
        "Am senzația că pericolul este permanent",
        "Nu mă mai simt în siguranță nicăieri"
    ],
    
    "Bulimie / Alimentație compulsivă": [
        "Mănânc foarte repede și în cantități mari",
        "Mă simt vinovat rușinat după ce mănânc",
        "Îmi este frică să nu mă îngraș",
        "Îmi provoc voma iau laxative după ce mănânc",
        "Viața mea se învârte în jurul mâncării",
        "Mănânc în secret ascuns",
        "Pierd controlul când mănânc",
        "Mănânc compulsiv și nu mă pot opri",
        "Vomit după ce mănânc",
        "Ascund faptul că mănânc în exces",
        "Simt vinovăție după ce mănânc",
        "Am pierderi de control asupra alimentației",
        
        "Mănânc chiar și când nu îmi este foame",
        "Folosesc diuretice sau laxative pentru a scăpa de calorii",
        "Îmi impun perioade stricte de înfometare",
        "Mă cântăresc obsesiv, de mai multe ori pe zi",
        "Mă gândesc la mâncare tot timpul",
        "Fac exerciții fizice excesive pentru a arde caloriile",
        "Mă simt ca într-un ciclu din care nu pot ieși",
        "Știu că comportamentul meu alimentar nu este normal",
        "Nu pot mânca în fața altor persoane",
        "Colecționez rețete și gătesc pentru alții fără să mănânc",
        "Cumpăr alimente special pentru episoadele de supraalimentare",
        "Simt o ușurare temporară când mănânc compulsiv",
        "Îmi petrec mult timp planificând episoadele de mâncat compulsiv",
        "Mănânc până simt disconfort fizic",
        "Încerc diverse diete, dar mereu cad în același tipar",
        "Mă simt blocat într-un ciclu de înfometare și supraalimentare",
        "Îmi ascund ambalajele de mâncare",
        "Cheltui mulți bani pe mâncare pentru episoadele de supraalimentare",
        "Evit evenimentele sociale unde e mâncare",
        "Simt că nu pot trăi fără acest comportament"
    ],
    
    "Tulburare obsesiv-compulsivă": [
        "Trebuie să verific de mai multe ori",
        "Am gânduri nedorite care nu-mi dau pace",
        "Simt nevoia să fac lucrurile într-o anumită ordine",
        "Mă tem de contaminare microbi murdărie",
        "Număr aranjez organizez tot timpul",
        "Știu că e irațional, dar nu pot să mă opresc",
        "Verific în mod repetat ușa sau gazul",
        "Mă spăl excesiv pe mâini",
        "Am ritualuri pe care trebuie să le respect",
        "Gânduri intruzive mă deranjează",
        
        "Simt nevoia să așez obiectele perfect simetric",
        "Am gânduri despre a face rău altora, deși nu vreau asta",
        "Repet acțiuni până când 'simt' că e corect",
        "Nu pot folosi toalete publice din cauza fricii de contaminare",
        "Mă preocupă constant gândul că am făcut ceva greșit",
        "Petrec ore verificând dacă am făcut o greșeală",
        "Nu pot să arunc lucruri vechi sau inutile",
        "Îmi iau măsuri extreme de precauție în activități zilnice",
        "Am nevoie de reasigurare constantă",
        "Trebuie să spun anumite cuvinte sau să număr până la un anumit număr",
        "Am gânduri blasfemice care mă sperie",
        "Recitesc aceleași paragrafe din nou și din nou",
        "Trebuie să ating anumite obiecte într-un anumit mod",
        "Am imagini mentale violente sau sexuale nedorite",
        "Mă tem că voi face ceva rușinos în public",
        "Trebuie să fac lucrurile până când 'simt' că e perfect",
        "Mă tem că voi contamina pe alții",
        "Fac ritualuri mentale complexe",
        "Mă spăl până când pielea devine roșie și crăpată",
        "Mă tem că voi pierde controlul și voi face ceva rău"
    ],
    
    "Tulburare de panică": [
        "Simt că voi muri am un atac de cord",
        "Nu pot să respir", "Mă sufoc",
        "Inima îmi bate foarte tare neregulat",
        "Am amețeli vertij", "Simt că leșin",
        "Tremur", "Transpir excesiv",
        "Mi-e frică să nu fac un atac în public",
        "Evit locurile de unde nu pot scăpa ușor",
        "Simt că nu mai pot respira brusc",
        "Palpitații și frică intensă bruscă",
        "Am atacuri de panică aparent fără motiv",
        "Frica de a muri dintr-o dată",
        
        "Simt că pierd controlul",
        "Am senzația că sunt detașat de realitate",
        "Simt furnicături în mâini și picioare",
        "Îmi este frică să nu înnebunesc în timpul atacului",
        "Nu pot sta singur de teamă să nu fac un atac",
        "Corpul meu devine rigid în timpul atacului",
        "Simt o spaimă inexplicabilă și copleșitoare",
        "Mă doare pieptul în timpul atacului",
        "Simt că sunt într-un coșmar din care nu mă pot trezi",
        "Mă simt înțepenit, țintuit la pământ",
        "Fug sau părăsesc brusc locul când începe atacul",
        "Am greață sau dureri abdominale în timpul atacului",
        "Evit situații care mi-au declanșat atacuri în trecut",
        "Trăiesc cu frica permanentă de următorul atac",
        "Îmi iau mereu apă și medicamente cu mine",
        "Verific mereu unde este cea mai apropiată ieșire",
        "Mi-e frică să nu fac un atac când conduc",
        "Nu mai pot merge în magazine sau spații închise",
        "Am dezvoltat frici secundare legate de situațiile în care am avut atacuri",
        "Simt că mor în timpul atacului"
    ],
    
    "Tulburări psihotice": [
        "Aud voci când sunt singur",
        "Sunt urmărit spionat",
        "Oamenii îmi pot citi gândurile",
        "Cineva îmi controlează acțiunile gândurile",
        "Primesc mesaje speciale de la TV radio",
        "Am puteri abilități speciale pe care alții nu le înțeleg",
        "Aud voci care nu există",
        "Cred că cineva mă urmărește",
        "Altcineva îmi controlează gândurile",
        "Văd lucruri pe care ceilalți nu le văd",
        
        "Vocile îmi comentează acțiunile",
        "Vocile îmi dau ordine pe care trebuie să le urmez",
        "Simt că gândurile mele sunt difuzate în exterior",
        "Am senzația că există un complot împotriva mea",
        "Simt că sunt înlocuit de o dublură sau un impostor",
        "Simt că anumite părți ale corpului meu sunt modificate sau străine",
        "Pot simți prezențe invizibile în jurul meu",
        "Simt mirosuri sau gusturi ciudate pe care alții nu le detectează",
        "Am senzații ciudate în corp, ca și cum aș fi electrocutat",
        "Simt că dispozitive sau implanturi îmi controlează corpul",
        "Obiectele par să-și schimbe forma sau dimensiunea",
        "Cred că anumite persoane nu sunt reale",
        "Simt că timpul curge diferit sau se oprește",
        "Primesc mesaje codificate din mediul înconjurător",
        "Cred că am fost ales pentru un scop special",
        "Oamenii din jur par falși sau roboți",
        "Simt că există conexiuni ascunse între evenimente aparent separate",
        "Cred că anumite organizații mă urmăresc prin dispozitive",
        "Simt că sunt într-o realitate alternativă sau simulată",
        "Am revelații sau înțelegeri cosmice speciale"
    ],
    
    "Agorafobie": [
        "Mi-e frică să ies din casă",
        "Evit locurile aglomerate transportul public",
        "Mă tem că voi face un atac de panică și nu voi putea scăpa",
        "Nu merg nicăieri fără o persoană de încredere",
        "Mă simt în siguranță doar acasă",
        "Am nevoie să știu unde sunt ieșirile toaletele",
        "Evit locurile aglomerate",
        "Mi-e frică să ies din casă",
        "Mă tem că nu pot scăpa din anumite locuri",
        "Transportul public mă sperie",
        
        "Îmi planific meticulos orice ieșire din casă",
        "Prefer să renunț la evenimente importante decât să risc să ies",
        "Trebuie să știu mereu unde este cel mai apropiat spital",
        "Nu pot traversa poduri sau tuneluri",
        "Evit să conduc pe autostrăzi sau în trafic",
        "Mă simt prins în capcană în ascensoare sau alte spații închise",
        "Refuz invitații la evenimente pentru că nu pot face față",
        "Îmi e frică să nu fiu observat având un atac de panică",
        "Nu pot sta la coadă în magazine",
        "Prefer să cumpăr online decât să ies din casă",
        "Am o zonă de siguranță în jurul casei în care mă simt ok",
        "Mă tem că voi avea o urgență medicală departe de ajutor",
        "Evit cinematografele și sălile de spectacol",
        "Nu pot merge la restaurant sau cafenea",
        "Mă tem că voi face ceva rușinos în public",
        "Nu pot călători cu avionul sau trenul",
        "Îmi e frică să nu fiu singur printre străini",
        "Mă tem că nu voi putea să ajung la toaletă la timp",
        "Iau mereu medicamente 'de siguranță' cu mine",
        "Am abandonat jobul din cauza fricii de a ieși din casă"
    ],
    
    "Fobie socială": [
        "Evit situațiile în care sunt observat",
        "Mi-e teamă că voi spune ceva stupid/jenant",
        "Tremur transpir mă înroșesc când sunt cu oameni",
        "Mi-e frică să nu fiu judecat criticat",
        "Evit să mănânc să scriu în fața altora",
        "Mi-e frică să vorbesc în public",
        "Mă simt judecat de ceilalți",
        "Transpir și tremur în fața oamenilor",
        "Evit interacțiunile sociale",
        
        "Mă tem să nu par anxios în fața altora",
        "Evit să fiu centrul atenției",
        "Mă tem să nu roșesc în public",
        "Mi-e frică să nu tremurul mâinilor să fie observat",
        "Nu pot folosi toaletele publice dacă e cineva în preajmă",
        "Evit să mă uit în ochii oamenilor",
        "Mă tem că vocea îmi va tremura când vorbesc",
        "Refuz invitații la evenimente sociale",
        "Evit să intru într-o încăpere unde toți sunt deja așezați",
        "Mă tem să nu transpir vizibil în fața altora",
        "Îmi fac griji cu săptămâni înainte de evenimente sociale",
        "Analizez obsesiv interacțiunile sociale după ce s-au întâmplat",
        "Nu pot suna oameni la telefon",
        "Evit să fac reclamații sau să-mi exprim nemulțumirea",
        "Mi-e greu să merg la interviu pentru un job",
        "Nu pot să mănânc în restaurante",
        "Mă tem că ceilalți vor observa anxietatea mea",
        "Evit să întreb indicații când m-am rătăcit",
        "Mi-e frică să nu fac pe mine din cauza anxietății",
        "Nu pot prezenta în fața colegilor sau a grupurilor"
    ],
    
    "Abuz / Dependență de alcool": [
        "Beau mai mult decât intenționez",
        "Am încercat să reduc să mă opresc, dar nu am reușit",
        "Îmi trebuie mai mult alcool pentru același efect",
        "Am probleme cu familia la serviciu din cauza băuturii",
        "Beau dimineața singur",
        "Mă simt vinovat după ce beau",
        "Nu-mi amintesc ce am făcut când am băut",
        "Beau ca să scap de stres",
        "Am pierdut controlul asupra consumului",
        "Nu pot să mă opresc din băut",
        "Mă simt rău când nu beau",

        "Mă trezesc cu tremurături dimineața",
        "Îmi ascund sticlele de alcool prin casă",
        "Mint despre cât de mult beau",
        "Mă gândesc la băutură mare parte din zi",
        "Am probleme de sănătate cauzate de alcool",
        "Am avut accidente sau probleme legale din cauza alcoolului",
        "Prietenii sau familia mi-au spus că ar trebui să reduc consumul",
        "Beau singur tot mai des",
        "Mă simt iritat când nu pot bea",
        "Am nevoie de o băutură dimineața pentru a funcționa",
        "Transpir și am greață când nu beau",
        "Nu pot să mă distrez fără alcool",
        "Am renunțat la activități care îmi plăceau pentru a bea",
        "Mă simt nesigur când nu am alcool la îndemână",
        "Beau înainte de evenimente sociale pentru curaj",
        "Mi-am amanettat sau vândut lucruri pentru a cumpăra alcool",
        "Beau în situații periculoase (de ex. înainte de a conduce)",
        "Continui să beau deși știu că am probleme medicale de la alcool",
        "Am avut blackout-uri (perioade de amnezie) din cauza alcoolului",
        "Simt că viața mea se învârte în jurul consumului de alcool"
    ],
    
    "Abuz / Dependență de medicamente": [
        "Iau mai multe medicamente decât mi-a prescris doctorul",
        "Am nevoie de doze tot mai mari pentru a simți efectul",
        "Mă simt rău când nu iau medicamentul",
        "Obțin rețete de la mai mulți medici",
        "Am încercat să mă opresc, dar nu pot",
        "Am nevoie constantă de pastile",
        "Nu pot funcționa fără medicamente",
        "Mi-am crescut singur doza",
        "Simt sevraj când nu iau medicamente",
        
        "Îmi petrec mult timp procurând, luând sau recuperându-mă de pe urma medicamentelor",
        "Folosesc medicamentele chiar și când îmi dau seama că îmi fac rău",
        "Am renunțat la activități importante din cauza medicamentelor",
        "Cumpăr medicamente de pe piața neagră",
        "Am probleme financiare din cauza cheltuielilor pe medicamente",
        "Îmi ascund medicamentele de familie",
        "Mint despre cantitatea de medicamente pe care o iau",
        "Am convulsii sau dureri intense când nu iau medicamentele",
        "Mă izolez de prieteni și familie",
        "Mi-am pierdut jobul din cauza efectelor medicamentelor",
        "Îmi petrec mult timp calculând când pot lua următoarea doză",
        "Iau medicamente pentru efecte diferite de cele pentru care au fost prescrise",
        "Am ajuns la urgență din cauza supradozajului",
        "Iau medicamente pentru a evita simptomele de sevraj",
        "Am dezvoltat toleranță și am nevoie de doze tot mai mari",
        "Continui să iau medicamente deși știu că îmi agravează problemele psihice",
        "Am încercat să falsific rețete",
        "Mă simt anxios când nu am medicamente suficiente",
        "Am împrumutat sau furat medicamente de la alții",
        "Am schimbat medicul când a refuzat să-mi mai prescrie medicamente"
    ],
    
    "Tulburare de anxietate generalizată": [
        "Mă îngrijorez excesiv pentru orice",
        "Nu pot controla îngrijorările",
        "Sunt tensionat agitat tot timpul",
        "Nu mă pot relaxa concentra",
        "Mă simt epuizat de atâta îngrijorare",
        "Mă gândesc mereu la ce ar putea merge prost",
        "Sunt iritabil și am dificultăți de somn",
        "Mă îngrijorez tot timpul",
        "Nu pot să mă relaxez niciodată",
        "Îmi imaginez mereu scenarii negative",
        "Orice mică problemă mă copleșește",
        
        "Am dureri musculare din cauza tensiunii",
        "Mă îngrijorez excesiv pentru sănătatea mea și a celor dragi",
        "Nu pot lua decizii de teamă să nu greșesc",
        "Simt că trebuie să fiu pregătit pentru orice situație",
        "Mă trezesc noaptea cu gânduri îngrijorătoare",
        "Verific telefoanele sau email-urile obsesiv",
        "Mă simt mereu în alertă, ca și cum ar urma o catastrofă",
        "Îmi fac griji pentru lucruri improbabile",
        "Am palpitații când mă gândesc la problemele mele",
        "Nu pot să mă bucur de prezent pentru că mă îngrijorez pentru viitor",
        "Îmi fac liste și planuri excesive pentru a controla anxietatea",
        "Caut reasigurare constantă de la cei din jur",
        "Mă îngrijorez că mă îngrijorez prea mult",
        "Simt un nod în stomac permanent",
        "Am dificultăți în a mă concentra din cauza gândurilor anxioase",
        "Simt că mintea mea nu se oprește niciodată",
        "Mă îngrijorez pentru situații care încă nu s-au întâmplat",
        "Analizez excesiv conversațiile și interacțiunile sociale",
        "Mă simt copleșit de sarcinile zilnice",
        "Simt că sunt mereu cu un pas în urma obligațiilor"
    ],
    
    "Tulburare de somatizare": [
        "Am dureri în tot corpul",
        "Doctorii nu găsesc nimic în neregulă cu mine",
        "Am avut probleme de sănătate toată viața",
        "Simptomele mele sunt reale, dar nimeni nu mă crede",
        "Am probleme digestive dureri cronice neexplicate",
        "Am consultat mulți specialiști fără rezultat",
        "Am dureri fără cauze medicale",
        "Doctorii spun că sunt bine, dar simt că nu",
        "Mă simt obosit mereu",
        "Am simptome diferite zilnic",
        
        "Simptomele mele se schimbă frecvent",
        "Sunt convins că doctorii ratează ceva important",
        "Simt că nimeni nu ia în serios simptomele mele",
        "Mă concentrez mult pe senzațiile corporale",
        "Simptomele mele se înrăutățesc când sunt stresat",
        "Îmi petrec mult timp la medic sau în spital",
        "Am dureri care se mută dintr-o parte în alta a corpului",
        "Folosesc multe medicamente pentru simptomele mele",
        "Mă simt marginalizat de sistemul medical",
        "Am simptome care afectează multiple sisteme ale corpului",
        "Dificultățile din viața mea par să-mi agraveze simptomele",
        "Mi-am pierdut încrederea în medici",
        "Simptomele mele îmi limitează sever viața socială și profesională",
        "Simt amorțeli și furnicături care vin și pleacă",
        "Am probleme de echilibru și amețeli inexplicabile",
        "Simt că nimeni nu înțelege prin ce trec",
        "Am încercat tot felul de tratamente alternative",
        "Simt că boala mea mă definește",
        "Sunt extrem de sensibil la medicamente și tratamente",
        "Viața mea se învârte în jurul simptomelor și tratamentelor"
    ],
    
    "Ipohondrie": [
        "Sunt convins că am o boală gravă",
        "Investigațiile medicale nu mă liniștesc",
        "Îmi verific corpul în mod constant pentru semne de boală",
        "Caut simptomele mele pe internet tot timpul",
        "Mă tem că doctorii au ratat ceva important",
        "Îmi fac griji pentru sănătate în fiecare zi",
        "Cred că am o boală gravă",
        "Verific constant simptome pe internet",
        "Fac frecvent analize medicale",
        "Fiecare durere mă panichează",
        
        "Interpretez orice simptom ca fiind ceva grav",
        "Am schimbat mai mulți medici pentru că nu m-au luat în serios",
        "Mă simt temporar liniștit după consultații, dar anxietatea revine repede",
        "Evit știrile despre boli pentru că mă sperie",
        "Am un dosar medical voluminos cu toate analizele mele",
        "Mi-e frică să nu am o boală nedetectabilă",
        "Îmi iau constant temperatura sau tensiunea",
        "Nu cred medicii când îmi spun că sunt sănătos",
        "Îmi fac griji că o durere minoră este semnul unei boli grave",
        "Am făcut toate investigațiile posibile pentru simptomele mele",
        "Sunt convins că am simptomele unei boli rare",
        "Verific în oglindă schimbările pielii sau alte semne",
        "Mi-e frică să nu am cancer sau altă boală terminală",
        "Simt că trebuie să fiu vigilent pentru a depista orice boală din timp",
        "Compar constant simptomele mele cu informații de pe internet",
        "Mă tem că voi muri subit din cauza unei boli nediagnosticate",
        "Întreb frecvent prietenii despre simptomele mele",
        "Mi-e frică să nu transmit boli inexistente celor dragi",
        "Am întrerupt activități din cauza fricii de îmbolnăvire",
        "Îmi monitorizez toate funcțiile corpului în detaliu"
    ]
}
# nlp = spacy.load("ro_core_news_lg")

# input_doc = nlp(input_sentence)

# best_match = None
# best_score = 0.0

# for disorder, templates in psychiatric_templates.items():
#     similarities = []
#     for phrase in templates:
#         template_doc = nlp(phrase)
#         score = input_doc.similarity(template_doc)
#         similarities.append(score)
#     avg_score = sum(similarities) / len(similarities)
#     if avg_score > best_score:
#         best_score = avg_score
#         best_match = disorder

# print(f"Cea mai apropiată afecțiune: {best_match} (scor: {best_score:.2f})")

model = SentenceTransformer('paraphrase-multilingual-MiniLM-L12-v2')
input_embedding = model.encode(input_sentence, convert_to_tensor=True)
scores = {}

for disorder, phrases in psychiatric_templates.items():
    embeddings = model.encode(phrases, convert_to_tensor=True)
    cosine_scores = util.cos_sim(input_embedding, embeddings)
    avg_score = cosine_scores.mean().item()
    scores[disorder] = avg_score
sorted_scores = sorted(scores.items(), key=lambda x: x[1], reverse=True)
for i in range(3):
    top_disorder, top_score = sorted_scores[i]
    print(f"{top_disorder} (Scor: {top_score:.4f})")