from classes.questions.data import questions_by_subscale

FIRST_TEXT_QUESTION: str = "Scrie câteva rânduri despre tine."
THRESHOLD: float = 0.3

from transformers import AutoTokenizer, AutoModel, AutoModelForSeq2SeqLM, logging
from huggingface_hub import login
import torch
import torch.nn.functional as F
logging.set_verbosity_error()

def get_embedding(text: str) -> torch.Tensor:
	inputs = mh_tokenizer(text, return_tensors="pt", truncation=True, padding=True)
	with torch.no_grad():
		outputs = mh_model(**inputs)
	cls_embedding = outputs.last_hidden_state[:, 0, :]
	return F.normalize(cls_embedding, p=2, dim=1)

mh_huggingface_token = "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"

login(mh_huggingface_token)

mh_name = "mental/mental-bert-base-uncased"
mh_tokenizer = AutoTokenizer.from_pretrained(mh_name, token=True)
mh_model = AutoModel.from_pretrained(mh_name, token=True)

tl_name = "BlackKakapo/opus-mt-ro-en"
tl_tokenizer = AutoTokenizer.from_pretrained(tl_name)
tl_model = AutoModelForSeq2SeqLM.from_pretrained(tl_name)

symptoms_per_subscale = {
	"Tulburarea depresivă majoră": [
		"I no longer find pleasure in anything",
		"I feel sad all the time",
		"I have no energy to do anything",
		"I feel useless",
		"I feel useless and hopeless",
		"I don't sleep well at night",
		"I cry for no reason",
		"I always feel guilty",
		"Life no longer has meaning",
		"I've isolated myself from friends",
		"I've isolated myself from family",
		"I've isolated myself from friends and family",
		"I can't concentrate on anything",
		"I've lost a lot of weight without trying",
		"I've gained a lot of weight without trying",
		"I'm no longer interested in what's happening around me",
		"I feel sluggish, like I'm moving through water",
		"I'm irritable",
		"I get angry easily",
		"I'm easy to anger",
		"I wake up very early and can't fall back asleep",
		"I feel exhausted all the time, no matter how much I sleep",
		"I often think about death",
		"I often think about suicide",
		"Everything feels like a huge effort",
		"I no longer care about my appearance",
		"I feel like nobody cares about me",
		"I feel an inner void that can't be filled",
		"Nothing brings me joy anymore",
		"I feel like a burden to others",
		"I find it hard to make even simple decisions",
		"I have memory and concentration problems",
		"I don't feel like getting out of bed in the morning",
		"I constantly have negative thoughts",
		"I no longer dream about the future",
	],
	"Tulburare de stres posttraumatic": [
		"I constantly relive what happened",
		"I have nightmares every night",
		"Loud noises scare me",
		"I avoid anything that reminds me of it",
		"I feel in danger all the time",
		"I have nightmares about what happened",
		"I relive the moment",
		"I feel like it's happening again",
		"I avoid places that remind me of it",
		"I avoid people who remind me of what happened",
		"I'm always on high alert",
		"I can never relax",
		"I get scared easily",
		"I jump at any noise",
		"I feel detached from others",
		"I feel alienated from others",
		"I can't remember important parts of what happened",
		"I have daytime flashbacks",
		"When I think about what happened, I tremble and sweat",
		"I can't sleep without the light on",
		"I've become very vigilant, always on guard",
		"I wake up screaming at night",
		"I avoid talking about what happened",
		"I feel like I'm not myself anymore after what happened",
		"I feel like my life stopped at the moment of the trauma",
		"I no longer feel emotions like I used to",
		"I get angry very quickly",
		"I have trouble remembering everyday things",
		"I can't feel joy anymore",
		"I can't love anymore",
		"The future feels short and dark",
		"I feel ashamed of what happened",
		"I blame myself for what happened",
		"I overreact to normal situations",
		"I feel like no one can understand what I've been through",
		"I can't make future plans anymore",
		"I feel like I'm always in danger",
		"I no longer feel safe anywhere",
	],
	"Bulimie / Alimentație compulsivă": [
		"I eat very quickly",
		"I eat a lot",
		"I feel guilty after eating",
		"I feel ashamed after eating",
		"I feel guilty and ashamed after eating",
		"I'm afraid of gaining weight",
		"I make myself vomit after eating",
		"I take laxatives after eating",
		"I make myself vomit or take laxatives after eating",
		"My life revolves around food",
		"I eat in secret",
		"I lose control when I eat",
		"I binge eat and can't stop",
		"I vomit after eating",
		"I hide the fact that I overeat",
		"I lose control over my eating",
		"I eat even when I'm not hungry",
		"I use diuretics to get rid of calories",
		"I use laxatives to get rid of calories",
		"I use diuretics or laxatives to get rid of calories",
		"I impose strict fasting periods on myself",
		"I weigh myself obsessively several times a day",
		"I think about food all the time",
		"I exercise excessively to burn calories",
		"I feel trapped in a cycle I can't escape",
		"I know my eating behavior isn't normal",
		"I can't eat in front of others",
		"I collect recipes and cook for others without eating myself",
		"I buy food especially for binge episodes",
		"I feel temporary relief when I binge eat",
		"I spend a lot of time planning binge episodes",
		"I eat until I feel physically uncomfortable",
		"I try various diets but always fall back into the same pattern",
		"I feel stuck in a cycle of starving and bingeing",
		"I hide my food wrappers",
		"I spend a lot of money on food for binge episodes",
		"I avoid social events where there's food",
		"I feel like I can't live without this behavior",
	],
	"Tulburare obsesiv-compulsivă": [
		"I have to check things multiple times",
		"I have unwanted thoughts that won't go away",
		"I feel the need to do things in a specific order",
		"I'm afraid of contamination",
		"I'm afraid of germs",
		"I'm afraid of dirt",
		"I'm afraid of contamination and germs",
		"I'm afraid of contamination and dirt",
		"I'm afraid of germs and dirt",
		"I'm afraid of contamination, germs, and dirt",
		"I constantly count things",
		"I constantly arrange things",
		"I constantly organize things",
		"I constantly count or arrange things",
		"I constantly arrange or organize things",
		"I constantly count or organize things",
		"I constantly count, arrange, or organize things",
		"I know it's irrational, but I can't stop",
		"I repeatedly check the door or gas",
		"I wash my hands excessively",
		"I have rituals I must follow",
		"Intrusive thoughts bother me",
		"I need to place objects perfectly symmetrically",
		"I have thoughts of harming others, even though I don't want to",
		"I repeat actions until they 'feel right'",
		"I can't use public toilets due to fear of contamination",
		"I'm constantly worried I did something wrong",
		"I spend hours checking if I made a mistake",
		"I can't throw away old or useless things",
		"I take extreme precautions in daily activities",
		"I need constant reassurance",
		"I must say certain words",
		"I must count to a specific number",
		"I must say certain words or count to a specific number",
		"I have blasphemous thoughts that scare me",
		"I reread the same paragraphs over and over",
		"I must touch certain objects in a specific way",
		"I have unwanted violent or sexual mental images",
		"I'm afraid of doing something embarrassing in public",
		"I have to do things until they 'feel' perfect",
		"I'm afraid I'll contaminate others",
		"I perform complex mental rituals",
		"I wash until my skin is red and cracked",
		"I'm afraid I'll lose control and do something bad",
	],
	"Tulburare de panică": [
		"I feel like I'm dying",
		"I feel like I'm having a heart attack",
		"I can't breathe",
		"I'm suffocating",
		"My heart beats very fast",
		"My heart beats irregularly",
		"I feel dizzy",
		"I feel like the room is spinning",
		"I feel like I'm going to faint",
		"I tremble",
		"I sweat excessively",
		"I'm afraid of having a panic attack in public",
		"I avoid places I can't easily escape from",
		"I suddenly feel like I can't breathe",
		"I have panic attacks for no clear reason",
		"I'm afraid ofs suddenly dying",
		"I feel like I'm losing control",
		"I feel detached from reality",
		"I feel tingling in my hands and feet",
		"I'm afraid I'll go crazy during an attack",
		"I can't stay alone for fear of having an attack",
		"My body becomes stiff during an attack",
		"I feel an overwhelming, inexplicable fear",
		"I feel chest pain during attacks",
		"I feel like I'm in a nightmare I can't wake up from",
		"I feel paralyzed, pinned to the ground",
		"I run or suddenly leave when the attack starts",
		"I feel nauseous abdominal pain during attacks",
		"I feel have abdominal pain during attacks",
		"I feel nauseous or have abdominal pain during attacks",
		"I avoid situations that triggered attacks in the past",
		"I live in constant fear of the next attack",
		"I always carry water and medication with me",
		"I always check where the nearest exit is",
		"I'm afraid of having an attack while driving",
		"I can no longer go into shops or enclosed spaces",
		"I've developed secondary fears related to previous attack situations",
		"I feel like I'm dying during the attack",
	],
	"Tulburări psihotice": [
		"I hear voices when I'm alone",
		"I feel watched",
		"I feel spied on",
		"I feel watched or spied on",
		"People can read my thoughts",
		"Someone controls my actions",
		"Somerhing controls my actions",
		"Someone controls my thoughts",
		"Somerhing controls my thoughts",
		"Someone controls my actions or thoughts",
		"Somerhing controls my actions or thoughts",
		"I receive special messages from the TV",
		"I receive special messages from the radio",
		"I have special powers that others don't understand",
		"I have abilities that others don't understand",
		"I hear voices that don't exist",
		"I believe someone is following me",
		"I see things others don't see",
		"Voices comment on my actions",
		"Voices give me commands I must follow",
		"I feel like my thoughts are broadcast outside",
		"I sense there's a conspiracy against me",
		"I feel like I've been replaced by a double or impostor",
		"I feel like parts of my body are altered or foreign",
		"I can sense invisible presences around me",
		"I perceive strange smells that others don't detect",
		"I perceive strange tastes that others don't detect",
		"I perceive strange smells or tastes that others don't detect",
		"I feel weird sensations in my body, like I'm being electrocuted",
		"I feel like devices control my body",
		"I feel like implants control my body",
		"I feel like devices or implants control my body",
		"Objects seem to change shape or size",
		"I believe some people aren't real",
		"I feel like time flows differently",
		"I receive encoded messages from my environment",
		"I believe I've been chosen for a special purpose",
		"People around me seem fake or robotic",
		"I feel there are hidden connections between unrelated events",
		"I believe certain organizations are tracking me through devices",
		"I feel like I'm in an alternate reality or simulation",
		"I have cosmic or special revelations",
	],
	"Agorafobie": [
		"I'm afraid to leave the house",
		"I avoid crowded places and public transport",
		"I'm afraid I'll have a panic attack",
		"I'm afraid I won't be able to escape",
		"I'm afraid I'll have a panic attack and won't be able to escape",
		"I don't go anywhere without a trusted person",
		"I only feel safe at home",
		"I need to know where the exits are",
		"I need to know where the bathrooms are",
		"I need to know where the exits and bathrooms are",
		"I avoid crowded places",
		"I'm scared to leave the house",
		"I'm afraid I can't escape certain places",
		"Public transport scares me",
		"I meticulously plan every trip outside",
		"I'd rather skip important events than risk going out",
		"I always need to know where the nearest hospital is",
		"I can't cross bridges or tunnels",
		"I can't go through tunnels",
		"I avoid driving on highways",
		"I avoid traffic",
		"I avoid driving in traffic",
		"I avoid driving on highways or in traffic",
		"I feel trapped in elevators",
		"I feel trapped in enclosed spaces",
		"I feel trapped in elevators and enclosed spaces",
		"I feel trapped in elevators or enclosed spaces",
		"I refuse invitations to events because I can't handle them",
		"I'm afraid people will see me having a panic attack",
		"I can't stand in line at stores",
		"I prefer shopping online instead of going out",
		"I have a safety zone around my home where I feel okay",
		"I'm afraid of having a medical emergency far from help",
		"I avoid cinemas and theaters",
		"I can't go to restaurants",
		"I can't go to cafés",
		"I'm afraid I'll do something embarrassing in public",
		"I can't travel by plane or train",
		"I'm afraid of being alone among strangers",
		"I'm afraid I won't reach a bathroom in time",
		"I always carry 'safety' medication with me",
		"I quit my job because of my fear of going outside",
	],
	"Fobie socială": [
		"I avoid situations where I'm being watched",
		"I'm afraid I'll say something stupid",
		"I'm afraid I'll say something embarrassing",
		"I'm afraid I'll say something stupid or embarrassing",
		"I tremble around people",
		"I sweat around people",
		"I blush around people",
		"I tremble and sweat around people",
		"I tremble and blush around people",
		"I sweat and blush around people",
		"I tremble, sweat and blush around people",
		"I'm afraid of being judged",
		"I'm afraid of being criticized",
		"I'm afraid of being judged or criticized",
		"I avoid eating in front of others",
		"I avoid writing in front of others",
		"I'm afraid to speak in public",
		"I feel judged by others",
		"I sweat and tremble in front of people",
		"I avoid social interactions",
		"I'm afraid to look anxious in front of others",
		"I avoid being the center of attention",
		"I'm afraid I'll blush in public",
		"I'm afraid people will notice my hands shaking",
		"I can't use public toilets if someone is nearby",
		"I avoid making eye contact",
		"I'm afraid my voice will tremble when I speak",
		"I refuse invitations to social events",
		"I avoid entering rooms where everyone is already seated",
		"I'm afraid I'll visibly sweat in front of others",
		"I worry for weeks before social events",
		"I obsessively analyze social interactions after they happen",
		"I can't call people on the phone",
		"I avoid complaining or expressing dissatisfaction",
		"I find it hard to attend job interviews",
		"I can't eat in restaurants",
		"I'm afraid others will notice my anxiety",
		"I avoid asking for directions when I'm lost",
		"I'm afraid I'll wet myself from anxiety",
		"I can't present in front of colleagues",
		"I can't present in front of groups",
		"I can't present in front of colleagues or groups",
	],
	"Abuz / Dependență de alcool": [
		"I drink more than I intend to",
		"I've tried to stop drinking, but I couldn't",
		"I have family problems because of drinking",
		"I have problems with work because of drinking",
		"I drink alone in the morning",
		"I feel guilty after drinking",
		"I don't remember what I did while drinking",
		"I drink to escape stress",
		"I've lost control over my drinking",
		"I can't stop drinking",
		"I feel sick when I don't drink",
		"I wake up shaking in the morning",
		"I hide alcohol bottles around the house",
		"I lie about how much I drink",
		"I think about alcohol most of the day",
		"I have health issues caused by alcohol",
		"I've had legal problems due to drinking",
		"I've had accidents problems due to drinking",
		"I've had accidents or legal problems due to drinking",
		"I've had accidents and legal problems due to drinking",
		"Friends have told me I should cut back on drinking",
		"My Family has told me I should cut back on drinking",
		"I drink alone more and more often",
		"I feel irritable when I can't drink",
		"I need a drink in the morning to function",
		"I sweat when I don't drink",
		"I feel nauseous when I don't drink",
		"I sweat and feel nauseous when I don't drink",
		"I can't have fun without alcohol",
		"I've given up activities I used to enjoy to drink",
		"I drink before social events for courage",
		"I've pawned or sold things to buy alcohol",
		"I keep drinking even though I know it harms my health",
		"I've had blackouts from drinking",
		"I feel like my life revolves around alcohol",
	],
	"Abuz / Dependență de medicamente": [
		"I take more medication than prescribed",
		"I feel sick when I don't take my medication",
		"I get prescriptions from multiple doctors",
		"I've tried to stop but I can't",
		"I constantly need pills",
		"I can't function without medication",
		"I've increased the dose on my own",
		"I experience withdrawal when not taking meds",
		"I spend a lot of time getting, using, or recovering from medication",
		"I keep taking meds even though I know they're harmful",
		"I've quit important activities due to meds",
		"I buy medication on the black market",
		"I have financial problems from spending on medication",
		"I hide meds from my family",
		"I lie about how much medication I take",
		"I have seizures or intense pain when I don't take medication",
		"I isolate myself from friends and family",
		"I lost my job because of medication",
		"I constantly calculate when I can take the next dose",
		"I take medication for effects other than prescribed",
		"I've ended up in the ER due to overdose",
		"I take meds to avoid withdrawal symptoms",
		"I've developed tolerance and need more and more",
		"I keep taking meds even though they worsen my mental health",
		"I tried to forge prescriptions",
		"I feel anxious when I don't have enough medication",
		"I've borrowed or stolen medication from others",
		"I changed doctors when one refused to prescribe more",
	],
	"Tulburare de anxietate generalizată": [
		"I worry excessively",
		"I worry excessively about everything",
		"I can't control my worries",
		"I'm tense all the time",
		"I'm restless all the time",
		"I'm tense and restless all the time",
		"I can't concentrate",
		"I can't relax",
		"I'm exhausted from worrying so much",
		"I'm always thinking about what could go wrong",
		"I'm irritable",
		"I have trouble sleeping",
		"I'm irritable and have trouble sleeping",
		"I'm always worrying",
		"I can never relax",
		"I constantly imagine negative scenarios",
		"Any small problem overwhelms me",
		"I have muscle pain due to tension",
		"I worry too much about my health",
		"I worry too much about loved ones",
		"I worry too much about my health and loved ones",
		"I can't make decisions for fear of making a mistake",
		"I feel like I must be prepared for anything",
		"I wake up at night with worrisome thoughts",
		"I obsessively check my phone",
		"I obsessively check my email",
		"I obsessively check my phone or email",
		"I obsessively check my phone and email",
		"I always feel on alert, like disaster is near",
		"I worry about unlikely things",
		"I get heart palpitations thinking about my problems",
		"I can't enjoy the present because I worry about the future",
		"I make excessive lists and plans to control my anxiety",
		"I constantly seek reassurance from those around me",
		"I worry that I worry too much",
		"I feel a permanent knot in my stomach",
		"I have trouble concentrating due to anxious thoughts",
		"My mind never stops racing",
		"I worry about situations that haven't even happened yet",
		"I overanalyze conversations and social interactions",
		"I feel overwhelmed by daily tasks",
		"I feel like I'm always one step behind on responsibilities",
	],
	"Tulburare de somatizare": [
		"I have pain all over my body",
		"Doctors can't find anything wrong with me",
		"I've had health problems my whole life",
		"My symptoms are real, but no one believes me",
		"I have digestive problems",
		"I have unexplained chronic pain",
		"I have digestive problems and unexplained chronic pain",
		"I've seen many specialists without results",
		"I have pain without medical cause",
		"Doctors say I'm fine, but I feel like I'm not",
		"I always feel tired",
		"My symptoms change every day",
		"My symptoms change frequently",
		"I'm convinced doctors are missing something important",
		"I feel like no one takes my symptoms seriously",
		"I focus a lot on bodily sensations",
		"My symptoms get worse when I'm stressed",
		"I spend a lot of time at the doctor",
		"I spend a lot of time in hospitals",
		"I have pain that moves around my body",
		"I use a lot of medication for my symptoms",
		"I feel marginalized by the medical system",
		"My symptoms affect multiple systems in my body",
		"Life difficulties seem to worsen my symptoms",
		"I've lost trust in doctors",
		"My symptoms severely limit my social and professional life",
		"I feel numbness and tingling that comes and goes",
		"I have unexplained balance issues and dizziness",
		"I feel like no one understands what I'm going through",
		"I've tried all kinds of alternative treatments",
		"I feel like my illness defines me",
		"I'm extremely sensitive to medications and treatments",
		"My life revolves around symptoms and treatments",
	],
	"Ipohondrie": [
		"I'm convinced I have a serious illness",
		"Medical tests don't reassure me",
		"I constantly check my body for signs of illness",
		"I'm always looking up my symptoms online",
		"I'm afraid doctors missed something important",
		"I worry about my health every day",
		"I believe I have a serious disease",
		"I constantly check symptoms online",
		"I get medical tests frequently",
		"Every ache or pain panics me",
		"I interpret any symptom as something serious",
		"I've changed doctors because they didn't take me seriously",
		"I feel reassured after consultations, but the anxiety soon returns",
		"I avoid news about diseases because it scares me",
		"I have a huge medical file with all my tests",
		"I'm afraid of having an undetectable illness",
		"I constantly check my temperature",
		"I constantly check my blood pressure",
		"I constantly check my temperature or blood pressure",
		"I constantly check my temperature and blood pressure",
		"I don't believe doctors when they say I'm healthy",
		"I worry that a small pain is a sign of a serious illness",
		"I've done every possible investigation for my symptoms",
		"I'm convinced I have symptoms of a rare disease",
		"I check the mirror for skin changes",
		"I check the mirror for signs of an illness",
		"I'm afraid I have cancer",
		"I'm afraid I have a terminal illness",
		"I feel I must stay vigilant to detect disease early",
		"I constantly compare my symptoms with online information",
		"I'm afraid I'll suddenly die from an undiagnosed disease",
		"I frequently ask friends about my symptoms",
		"I'm afraid I'll transmit nonexistent diseases to loved ones",
		"I've quit activities because of fear of getting sick",
		"I monitor all my bodily functions in detail",
	],
}
symptoms_embeddings_per_subscale = {k: torch.cat(list(map(get_embedding, v))) for k, v in symptoms_per_subscale.items()}
def get_subscale_weights(texts: dict[str, str], excluded_subscales: list[str]) -> dict[str, float]:
	def translate_ro_to_en(text: str) -> str:
		inputs = tl_tokenizer(text, return_tensors="pt", padding=True, truncation=True)
		translated = tl_model.generate(**inputs)
		return tl_tokenizer.decode(translated[0], skip_special_tokens=True)

	romanian_input = "".join(f"{q}\n{a}\n\n" for q, a in texts.items())
	english_input = translate_ro_to_en(romanian_input)
	input_emb = get_embedding(english_input)
	scores = {}
	for subscale, symptoms_emb in symptoms_embeddings_per_subscale.items():
		if subscale in excluded_subscales: continue
		sim = F.cosine_similarity(input_emb, symptoms_emb).mean().item()
		scores[subscale] = round(sim, 3)
	return scores

def select_next_subscale(first_text: str, answers_by_subscale: dict[str, dict[int, bool | list[bool] | str]]) -> str | None:
	texts: dict[str, str] = {FIRST_TEXT_QUESTION: first_text} | {
		q: a for _, qs in answers_by_subscale.items() for q, a in qs.items() if isinstance(a, str)
	}
	subscales_to_exclude = list(filter(lambda kvp: len(kvp[1]) > 0, answers_by_subscale))
	weights_of_subscales = get_subscale_weights(texts, subscales_to_exclude)
	if len(weights_of_subscales) == 0: return None
	for k, v in weights_of_subscales.items():
		print(f"{k} => {v}")
	max_subscale = max(weights_of_subscales, key=weights_of_subscales.get)
	return max_subscale if weights_of_subscales[max_subscale] >= THRESHOLD else None
